package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaAssuntoMidiaId generated by hbm2java
 */
@Embeddable
public class TaAssuntoMidiaId  implements java.io.Serializable {


     private int codAssunto;
     private int codMidia;

    public TaAssuntoMidiaId() {
    }

    public TaAssuntoMidiaId(int codAssunto, int codMidia) {
       this.codAssunto = codAssunto;
       this.codMidia = codMidia;
    }
   


    @Column(name="cod_assunto", nullable=false)
    public int getCodAssunto() {
        return this.codAssunto;
    }
    
    public void setCodAssunto(int codAssunto) {
        this.codAssunto = codAssunto;
    }


    @Column(name="cod_midia", nullable=false)
    public int getCodMidia() {
        return this.codMidia;
    }
    
    public void setCodMidia(int codMidia) {
        this.codMidia = codMidia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaAssuntoMidiaId) ) return false;
		 TaAssuntoMidiaId castOther = ( TaAssuntoMidiaId ) other; 
         
		 return (this.getCodAssunto()==castOther.getCodAssunto())
 && (this.getCodMidia()==castOther.getCodMidia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodAssunto();
         result = 37 * result + this.getCodMidia();
         return result;
   }   


}


