package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaUsuarioFaculdade generated by hbm2java
 */
@Entity
@Table(name="ta_usuario_faculdade"
    ,catalog="estreaming"
)
public class TaUsuarioFaculdade  implements java.io.Serializable {


     private TaUsuarioFaculdadeId id;
     private TbFaculdade tbFaculdade;
     private TbUsuario tbUsuario;
     private boolean stsUsuarioFaculdade;

    public TaUsuarioFaculdade() {
    }

    public TaUsuarioFaculdade(TaUsuarioFaculdadeId id, TbFaculdade tbFaculdade, TbUsuario tbUsuario, boolean stsUsuarioFaculdade) {
       this.id = id;
       this.tbFaculdade = tbFaculdade;
       this.tbUsuario = tbUsuario;
       this.stsUsuarioFaculdade = stsUsuarioFaculdade;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codUsuario", column=@Column(name="cod_usuario", nullable=false) ), 
        @AttributeOverride(name="codFaculdade", column=@Column(name="cod_faculdade", nullable=false) ) } )
    public TaUsuarioFaculdadeId getId() {
        return this.id;
    }
    
    public void setId(TaUsuarioFaculdadeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_faculdade", nullable=false, insertable=false, updatable=false)
    public TbFaculdade getTbFaculdade() {
        return this.tbFaculdade;
    }
    
    public void setTbFaculdade(TbFaculdade tbFaculdade) {
        this.tbFaculdade = tbFaculdade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_usuario", nullable=false, insertable=false, updatable=false)
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }

    
    @Column(name="sts_usuario_faculdade", nullable=false)
    public boolean isStsUsuarioFaculdade() {
        return this.stsUsuarioFaculdade;
    }
    
    public void setStsUsuarioFaculdade(boolean stsUsuarioFaculdade) {
        this.stsUsuarioFaculdade = stsUsuarioFaculdade;
    }




}


