package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaUsuarioFaculdadeId generated by hbm2java
 */
@Embeddable
public class TaUsuarioFaculdadeId  implements java.io.Serializable {


     private int codUsuario;
     private int codFaculdade;

    public TaUsuarioFaculdadeId() {
    }

    public TaUsuarioFaculdadeId(int codUsuario, int codFaculdade) {
       this.codUsuario = codUsuario;
       this.codFaculdade = codFaculdade;
    }
   


    @Column(name="cod_usuario", nullable=false)
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }


    @Column(name="cod_faculdade", nullable=false)
    public int getCodFaculdade() {
        return this.codFaculdade;
    }
    
    public void setCodFaculdade(int codFaculdade) {
        this.codFaculdade = codFaculdade;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaUsuarioFaculdadeId) ) return false;
		 TaUsuarioFaculdadeId castOther = ( TaUsuarioFaculdadeId ) other; 
         
		 return (this.getCodUsuario()==castOther.getCodUsuario())
 && (this.getCodFaculdade()==castOther.getCodFaculdade());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodUsuario();
         result = 37 * result + this.getCodFaculdade();
         return result;
   }   


}


