package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbCompletarAlternativas generated by hbm2java
 */
@Entity
@Table(name="tb_completar_alternativas"
    ,catalog="estreaming"
)
public class TbCompletarAlternativas  implements java.io.Serializable {


     private Integer idtCompletarAlternativas;
     private TbCompletar tbCompletar;
     private int ordCompletarAlternativas;
     private String txtPalavra;
     private boolean stsCompletarAlternativas;

    public TbCompletarAlternativas() {
    }

    public TbCompletarAlternativas(TbCompletar tbCompletar, int ordCompletarAlternativas, String txtPalavra, boolean stsCompletarAlternativas) {
       this.tbCompletar = tbCompletar;
       this.ordCompletarAlternativas = ordCompletarAlternativas;
       this.txtPalavra = txtPalavra;
       this.stsCompletarAlternativas = stsCompletarAlternativas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_completar_alternativas", unique=true, nullable=false)
    public Integer getIdtCompletarAlternativas() {
        return this.idtCompletarAlternativas;
    }
    
    public void setIdtCompletarAlternativas(Integer idtCompletarAlternativas) {
        this.idtCompletarAlternativas = idtCompletarAlternativas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_completar", nullable=false)
    public TbCompletar getTbCompletar() {
        return this.tbCompletar;
    }
    
    public void setTbCompletar(TbCompletar tbCompletar) {
        this.tbCompletar = tbCompletar;
    }

    
    @Column(name="ord_completar_alternativas", nullable=false)
    public int getOrdCompletarAlternativas() {
        return this.ordCompletarAlternativas;
    }
    
    public void setOrdCompletarAlternativas(int ordCompletarAlternativas) {
        this.ordCompletarAlternativas = ordCompletarAlternativas;
    }

    
    @Column(name="txt_palavra", nullable=false, length=65535)
    public String getTxtPalavra() {
        return this.txtPalavra;
    }
    
    public void setTxtPalavra(String txtPalavra) {
        this.txtPalavra = txtPalavra;
    }

    
    @Column(name="sts_completar_alternativas", nullable=false)
    public boolean isStsCompletarAlternativas() {
        return this.stsCompletarAlternativas;
    }
    
    public void setStsCompletarAlternativas(boolean stsCompletarAlternativas) {
        this.stsCompletarAlternativas = stsCompletarAlternativas;
    }




}


