package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbFaculdade generated by hbm2java
 */
@Entity
@Table(name="tb_faculdade"
    ,catalog="estreaming"
)
public class TbFaculdade  implements java.io.Serializable {


     private Integer idtFaculdade;
     private TbInstituicao tbInstituicao;
     private String nmeFaculdade;
     private boolean stsFaculdade;
     private Date dtaInsercao;
     private String codUsuarioAdmin;
     private Set<TbCurso> tbCursos = new HashSet<TbCurso>(0);
     private Set<TaUsuarioFaculdade> taUsuarioFaculdades = new HashSet<TaUsuarioFaculdade>(0);

    public TbFaculdade() {
    }

	
    public TbFaculdade(TbInstituicao tbInstituicao, String nmeFaculdade, boolean stsFaculdade, Date dtaInsercao, String codUsuarioAdmin) {
        this.tbInstituicao = tbInstituicao;
        this.nmeFaculdade = nmeFaculdade;
        this.stsFaculdade = stsFaculdade;
        this.dtaInsercao = dtaInsercao;
        this.codUsuarioAdmin = codUsuarioAdmin;
    }
    public TbFaculdade(TbInstituicao tbInstituicao, String nmeFaculdade, boolean stsFaculdade, Date dtaInsercao, String codUsuarioAdmin, Set<TbCurso> tbCursos, Set<TaUsuarioFaculdade> taUsuarioFaculdades) {
       this.tbInstituicao = tbInstituicao;
       this.nmeFaculdade = nmeFaculdade;
       this.stsFaculdade = stsFaculdade;
       this.dtaInsercao = dtaInsercao;
       this.codUsuarioAdmin = codUsuarioAdmin;
       this.tbCursos = tbCursos;
       this.taUsuarioFaculdades = taUsuarioFaculdades;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_faculdade", unique=true, nullable=false)
    public Integer getIdtFaculdade() {
        return this.idtFaculdade;
    }
    
    public void setIdtFaculdade(Integer idtFaculdade) {
        this.idtFaculdade = idtFaculdade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_instituicao", nullable=false)
    public TbInstituicao getTbInstituicao() {
        return this.tbInstituicao;
    }
    
    public void setTbInstituicao(TbInstituicao tbInstituicao) {
        this.tbInstituicao = tbInstituicao;
    }

    
    @Column(name="nme_faculdade", nullable=false, length=45)
    public String getNmeFaculdade() {
        return this.nmeFaculdade;
    }
    
    public void setNmeFaculdade(String nmeFaculdade) {
        this.nmeFaculdade = nmeFaculdade;
    }

    
    @Column(name="sts_faculdade", nullable=false)
    public boolean isStsFaculdade() {
        return this.stsFaculdade;
    }
    
    public void setStsFaculdade(boolean stsFaculdade) {
        this.stsFaculdade = stsFaculdade;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_insercao", nullable=false, length=19)
    public Date getDtaInsercao() {
        return this.dtaInsercao;
    }
    
    public void setDtaInsercao(Date dtaInsercao) {
        this.dtaInsercao = dtaInsercao;
    }

    
    @Column(name="cod_usuario_admin", nullable=false, length=45)
    public String getCodUsuarioAdmin() {
        return this.codUsuarioAdmin;
    }
    
    public void setCodUsuarioAdmin(String codUsuarioAdmin) {
        this.codUsuarioAdmin = codUsuarioAdmin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbFaculdade")
    public Set<TbCurso> getTbCursos() {
        return this.tbCursos;
    }
    
    public void setTbCursos(Set<TbCurso> tbCursos) {
        this.tbCursos = tbCursos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbFaculdade")
    public Set<TaUsuarioFaculdade> getTaUsuarioFaculdades() {
        return this.taUsuarioFaculdades;
    }
    
    public void setTaUsuarioFaculdades(Set<TaUsuarioFaculdade> taUsuarioFaculdades) {
        this.taUsuarioFaculdades = taUsuarioFaculdades;
    }




}


