package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbInstituicao generated by hbm2java
 */
@Entity
@Table(name="tb_instituicao"
    ,catalog="estreaming"
)
public class TbInstituicao  implements java.io.Serializable {


     private Integer idtInstituicao;
     private String cnpjInstituicao;
     private String nmeInstituicao;
     private String endInstituicao;
     private String cepInstituicao;
     private String telInstituicao1;
     private String telInstituicao2;
     private String emlInstituicao;
     private String urlInstituicao;
     private Date dtaInsercao;
     private boolean stsInstituicao;
     private String razaoSocial;
     private Set<TbFaculdade> tbFaculdades = new HashSet<TbFaculdade>(0);

    public TbInstituicao() {
    }

	
    public TbInstituicao(String cnpjInstituicao, String nmeInstituicao, String endInstituicao, String cepInstituicao, String telInstituicao1, String emlInstituicao, Date dtaInsercao, boolean stsInstituicao, String razaoSocial) {
        this.cnpjInstituicao = cnpjInstituicao;
        this.nmeInstituicao = nmeInstituicao;
        this.endInstituicao = endInstituicao;
        this.cepInstituicao = cepInstituicao;
        this.telInstituicao1 = telInstituicao1;
        this.emlInstituicao = emlInstituicao;
        this.dtaInsercao = dtaInsercao;
        this.stsInstituicao = stsInstituicao;
        this.razaoSocial = razaoSocial;
    }
    public TbInstituicao(String cnpjInstituicao, String nmeInstituicao, String endInstituicao, String cepInstituicao, String telInstituicao1, String telInstituicao2, String emlInstituicao, String urlInstituicao, Date dtaInsercao, boolean stsInstituicao, String razaoSocial, Set<TbFaculdade> tbFaculdades) {
       this.cnpjInstituicao = cnpjInstituicao;
       this.nmeInstituicao = nmeInstituicao;
       this.endInstituicao = endInstituicao;
       this.cepInstituicao = cepInstituicao;
       this.telInstituicao1 = telInstituicao1;
       this.telInstituicao2 = telInstituicao2;
       this.emlInstituicao = emlInstituicao;
       this.urlInstituicao = urlInstituicao;
       this.dtaInsercao = dtaInsercao;
       this.stsInstituicao = stsInstituicao;
       this.razaoSocial = razaoSocial;
       this.tbFaculdades = tbFaculdades;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_instituicao", unique=true, nullable=false)
    public Integer getIdtInstituicao() {
        return this.idtInstituicao;
    }
    
    public void setIdtInstituicao(Integer idtInstituicao) {
        this.idtInstituicao = idtInstituicao;
    }

    
    @Column(name="cnpj_instituicao", nullable=false, length=18)
    public String getCnpjInstituicao() {
        return this.cnpjInstituicao;
    }
    
    public void setCnpjInstituicao(String cnpjInstituicao) {
        this.cnpjInstituicao = cnpjInstituicao;
    }

    
    @Column(name="nme_instituicao", nullable=false, length=80)
    public String getNmeInstituicao() {
        return this.nmeInstituicao;
    }
    
    public void setNmeInstituicao(String nmeInstituicao) {
        this.nmeInstituicao = nmeInstituicao;
    }

    
    @Column(name="end_instituicao", nullable=false, length=100)
    public String getEndInstituicao() {
        return this.endInstituicao;
    }
    
    public void setEndInstituicao(String endInstituicao) {
        this.endInstituicao = endInstituicao;
    }

    
    @Column(name="cep_instituicao", nullable=false, length=10)
    public String getCepInstituicao() {
        return this.cepInstituicao;
    }
    
    public void setCepInstituicao(String cepInstituicao) {
        this.cepInstituicao = cepInstituicao;
    }

    
    @Column(name="tel_instituicao_1", nullable=false, length=11)
    public String getTelInstituicao1() {
        return this.telInstituicao1;
    }
    
    public void setTelInstituicao1(String telInstituicao1) {
        this.telInstituicao1 = telInstituicao1;
    }

    
    @Column(name="tel_instituicao_2", length=11)
    public String getTelInstituicao2() {
        return this.telInstituicao2;
    }
    
    public void setTelInstituicao2(String telInstituicao2) {
        this.telInstituicao2 = telInstituicao2;
    }

    
    @Column(name="eml_instituicao", nullable=false, length=80)
    public String getEmlInstituicao() {
        return this.emlInstituicao;
    }
    
    public void setEmlInstituicao(String emlInstituicao) {
        this.emlInstituicao = emlInstituicao;
    }

    
    @Column(name="url_instituicao", length=80)
    public String getUrlInstituicao() {
        return this.urlInstituicao;
    }
    
    public void setUrlInstituicao(String urlInstituicao) {
        this.urlInstituicao = urlInstituicao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_insercao", nullable=false, length=19)
    public Date getDtaInsercao() {
        return this.dtaInsercao;
    }
    
    public void setDtaInsercao(Date dtaInsercao) {
        this.dtaInsercao = dtaInsercao;
    }

    
    @Column(name="sts_instituicao", nullable=false)
    public boolean isStsInstituicao() {
        return this.stsInstituicao;
    }
    
    public void setStsInstituicao(boolean stsInstituicao) {
        this.stsInstituicao = stsInstituicao;
    }

    
    @Column(name="razao_social", nullable=false, length=100)
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbInstituicao")
    public Set<TbFaculdade> getTbFaculdades() {
        return this.tbFaculdades;
    }
    
    public void setTbFaculdades(Set<TbFaculdade> tbFaculdades) {
        this.tbFaculdades = tbFaculdades;
    }




}


