package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbMultEscolha generated by hbm2java
 */
@Entity
@Table(name="tb_mult_escolha"
    ,catalog="estreaming"
)
public class TbMultEscolha  implements java.io.Serializable {


     private Integer idtMultEscolha;
     private TbAssunto tbAssunto;
     private TbTipoQuestao tbTipoQuestao;
     private String txtEnunciado;
     private boolean stsMultEscolha;
     private int ordMultEscolha;
     private Date dtaInsercao;
     private String vlrQuestao;
     private char flgFinalizada;
     private Set<TbMultAlternativas> tbMultAlternativases = new HashSet<TbMultAlternativas>(0);

    public TbMultEscolha() {
    }

	
    public TbMultEscolha(TbAssunto tbAssunto, TbTipoQuestao tbTipoQuestao, String txtEnunciado, boolean stsMultEscolha, int ordMultEscolha, Date dtaInsercao, String vlrQuestao, char flgFinalizada) {
        this.tbAssunto = tbAssunto;
        this.tbTipoQuestao = tbTipoQuestao;
        this.txtEnunciado = txtEnunciado;
        this.stsMultEscolha = stsMultEscolha;
        this.ordMultEscolha = ordMultEscolha;
        this.dtaInsercao = dtaInsercao;
        this.vlrQuestao = vlrQuestao;
        this.flgFinalizada = flgFinalizada;
    }
    public TbMultEscolha(TbAssunto tbAssunto, TbTipoQuestao tbTipoQuestao, String txtEnunciado, boolean stsMultEscolha, int ordMultEscolha, Date dtaInsercao, String vlrQuestao, char flgFinalizada, Set<TbMultAlternativas> tbMultAlternativases) {
       this.tbAssunto = tbAssunto;
       this.tbTipoQuestao = tbTipoQuestao;
       this.txtEnunciado = txtEnunciado;
       this.stsMultEscolha = stsMultEscolha;
       this.ordMultEscolha = ordMultEscolha;
       this.dtaInsercao = dtaInsercao;
       this.vlrQuestao = vlrQuestao;
       this.flgFinalizada = flgFinalizada;
       this.tbMultAlternativases = tbMultAlternativases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_mult_escolha", unique=true, nullable=false)
    public Integer getIdtMultEscolha() {
        return this.idtMultEscolha;
    }
    
    public void setIdtMultEscolha(Integer idtMultEscolha) {
        this.idtMultEscolha = idtMultEscolha;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_assunto", nullable=false)
    public TbAssunto getTbAssunto() {
        return this.tbAssunto;
    }
    
    public void setTbAssunto(TbAssunto tbAssunto) {
        this.tbAssunto = tbAssunto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_tipo_questao", nullable=false)
    public TbTipoQuestao getTbTipoQuestao() {
        return this.tbTipoQuestao;
    }
    
    public void setTbTipoQuestao(TbTipoQuestao tbTipoQuestao) {
        this.tbTipoQuestao = tbTipoQuestao;
    }

    
    @Column(name="txt_enunciado", nullable=false, length=65535)
    public String getTxtEnunciado() {
        return this.txtEnunciado;
    }
    
    public void setTxtEnunciado(String txtEnunciado) {
        this.txtEnunciado = txtEnunciado;
    }

    
    @Column(name="sts_mult_escolha", nullable=false)
    public boolean isStsMultEscolha() {
        return this.stsMultEscolha;
    }
    
    public void setStsMultEscolha(boolean stsMultEscolha) {
        this.stsMultEscolha = stsMultEscolha;
    }

    
    @Column(name="ord_mult_escolha", nullable=false)
    public int getOrdMultEscolha() {
        return this.ordMultEscolha;
    }
    
    public void setOrdMultEscolha(int ordMultEscolha) {
        this.ordMultEscolha = ordMultEscolha;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_insercao", nullable=false, length=19)
    public Date getDtaInsercao() {
        return this.dtaInsercao;
    }
    
    public void setDtaInsercao(Date dtaInsercao) {
        this.dtaInsercao = dtaInsercao;
    }

    
    @Column(name="vlr_questao", nullable=false, length=45)
    public String getVlrQuestao() {
        return this.vlrQuestao;
    }
    
    public void setVlrQuestao(String vlrQuestao) {
        this.vlrQuestao = vlrQuestao;
    }

    
    @Column(name="flg_finalizada", nullable=false, length=1)
    public char getFlgFinalizada() {
        return this.flgFinalizada;
    }
    
    public void setFlgFinalizada(char flgFinalizada) {
        this.flgFinalizada = flgFinalizada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbMultEscolha")
    public Set<TbMultAlternativas> getTbMultAlternativases() {
        return this.tbMultAlternativases;
    }
    
    public void setTbMultAlternativases(Set<TbMultAlternativas> tbMultAlternativases) {
        this.tbMultAlternativases = tbMultAlternativases;
    }




}


