package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbSomatorio generated by hbm2java
 */
@Entity
@Table(name="tb_somatorio"
    ,catalog="estreaming"
)
public class TbSomatorio  implements java.io.Serializable {


     private Integer idtSomatorio;
     private TbAssunto tbAssunto;
     private TbTipoQuestao tbTipoQuestao;
     private String txtEnunciado;
     private boolean stsSomatorio;
     private int soma;
     private int ordSomatorio;
     private Date dtaInsercao;
     private char flgFinalizada;
     private Set<TbSomatorioAlternativas> tbSomatorioAlternativases = new HashSet<TbSomatorioAlternativas>(0);

    public TbSomatorio() {
    }

	
    public TbSomatorio(TbAssunto tbAssunto, TbTipoQuestao tbTipoQuestao, String txtEnunciado, boolean stsSomatorio, int soma, int ordSomatorio, Date dtaInsercao, char flgFinalizada) {
        this.tbAssunto = tbAssunto;
        this.tbTipoQuestao = tbTipoQuestao;
        this.txtEnunciado = txtEnunciado;
        this.stsSomatorio = stsSomatorio;
        this.soma = soma;
        this.ordSomatorio = ordSomatorio;
        this.dtaInsercao = dtaInsercao;
        this.flgFinalizada = flgFinalizada;
    }
    public TbSomatorio(TbAssunto tbAssunto, TbTipoQuestao tbTipoQuestao, String txtEnunciado, boolean stsSomatorio, int soma, int ordSomatorio, Date dtaInsercao, char flgFinalizada, Set<TbSomatorioAlternativas> tbSomatorioAlternativases) {
       this.tbAssunto = tbAssunto;
       this.tbTipoQuestao = tbTipoQuestao;
       this.txtEnunciado = txtEnunciado;
       this.stsSomatorio = stsSomatorio;
       this.soma = soma;
       this.ordSomatorio = ordSomatorio;
       this.dtaInsercao = dtaInsercao;
       this.flgFinalizada = flgFinalizada;
       this.tbSomatorioAlternativases = tbSomatorioAlternativases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_somatorio", unique=true, nullable=false)
    public Integer getIdtSomatorio() {
        return this.idtSomatorio;
    }
    
    public void setIdtSomatorio(Integer idtSomatorio) {
        this.idtSomatorio = idtSomatorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_assunto", nullable=false)
    public TbAssunto getTbAssunto() {
        return this.tbAssunto;
    }
    
    public void setTbAssunto(TbAssunto tbAssunto) {
        this.tbAssunto = tbAssunto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_tipo_questao", nullable=false)
    public TbTipoQuestao getTbTipoQuestao() {
        return this.tbTipoQuestao;
    }
    
    public void setTbTipoQuestao(TbTipoQuestao tbTipoQuestao) {
        this.tbTipoQuestao = tbTipoQuestao;
    }

    
    @Column(name="txt_enunciado", nullable=false, length=65535)
    public String getTxtEnunciado() {
        return this.txtEnunciado;
    }
    
    public void setTxtEnunciado(String txtEnunciado) {
        this.txtEnunciado = txtEnunciado;
    }

    
    @Column(name="sts_somatorio", nullable=false)
    public boolean isStsSomatorio() {
        return this.stsSomatorio;
    }
    
    public void setStsSomatorio(boolean stsSomatorio) {
        this.stsSomatorio = stsSomatorio;
    }

    
    @Column(name="soma", nullable=false)
    public int getSoma() {
        return this.soma;
    }
    
    public void setSoma(int soma) {
        this.soma = soma;
    }

    
    @Column(name="ord_somatorio", nullable=false)
    public int getOrdSomatorio() {
        return this.ordSomatorio;
    }
    
    public void setOrdSomatorio(int ordSomatorio) {
        this.ordSomatorio = ordSomatorio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_insercao", nullable=false, length=19)
    public Date getDtaInsercao() {
        return this.dtaInsercao;
    }
    
    public void setDtaInsercao(Date dtaInsercao) {
        this.dtaInsercao = dtaInsercao;
    }

    
    @Column(name="flg_finalizada", nullable=false, length=1)
    public char getFlgFinalizada() {
        return this.flgFinalizada;
    }
    
    public void setFlgFinalizada(char flgFinalizada) {
        this.flgFinalizada = flgFinalizada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbSomatorio")
    public Set<TbSomatorioAlternativas> getTbSomatorioAlternativases() {
        return this.tbSomatorioAlternativases;
    }
    
    public void setTbSomatorioAlternativases(Set<TbSomatorioAlternativas> tbSomatorioAlternativases) {
        this.tbSomatorioAlternativases = tbSomatorioAlternativases;
    }




}


