package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaDisciplinaCursos generated by hbm2java
 */
@Entity
@Table(name="ta_disciplina_cursos"
    ,catalog="estreaming"
)
public class TaDisciplinaCursos  implements java.io.Serializable {


     private TaDisciplinaCursosId id;
     private TbCurso tbCurso;
     private TbDisciplina tbDisciplina;
     private boolean stsDisciplinaCursos;

    public TaDisciplinaCursos() {
    }

    public TaDisciplinaCursos(TaDisciplinaCursosId id, TbCurso tbCurso, TbDisciplina tbDisciplina, boolean stsDisciplinaCursos) {
       this.id = id;
       this.tbCurso = tbCurso;
       this.tbDisciplina = tbDisciplina;
       this.stsDisciplinaCursos = stsDisciplinaCursos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codDisciplina", column=@Column(name="cod_disciplina", nullable=false) ), 
        @AttributeOverride(name="codCurso", column=@Column(name="cod_curso", nullable=false) ) } )
    public TaDisciplinaCursosId getId() {
        return this.id;
    }
    
    public void setId(TaDisciplinaCursosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_curso", nullable=false, insertable=false, updatable=false)
    public TbCurso getTbCurso() {
        return this.tbCurso;
    }
    
    public void setTbCurso(TbCurso tbCurso) {
        this.tbCurso = tbCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_disciplina", nullable=false, insertable=false, updatable=false)
    public TbDisciplina getTbDisciplina() {
        return this.tbDisciplina;
    }
    
    public void setTbDisciplina(TbDisciplina tbDisciplina) {
        this.tbDisciplina = tbDisciplina;
    }

    
    @Column(name="sts_disciplina_cursos", nullable=false)
    public boolean isStsDisciplinaCursos() {
        return this.stsDisciplinaCursos;
    }
    
    public void setStsDisciplinaCursos(boolean stsDisciplinaCursos) {
        this.stsDisciplinaCursos = stsDisciplinaCursos;
    }




}


