package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaDisciplinaCursosId generated by hbm2java
 */
@Embeddable
public class TaDisciplinaCursosId  implements java.io.Serializable {


     private int codDisciplina;
     private int codCurso;

    public TaDisciplinaCursosId() {
    }

    public TaDisciplinaCursosId(int codDisciplina, int codCurso) {
       this.codDisciplina = codDisciplina;
       this.codCurso = codCurso;
    }
   


    @Column(name="cod_disciplina", nullable=false)
    public int getCodDisciplina() {
        return this.codDisciplina;
    }
    
    public void setCodDisciplina(int codDisciplina) {
        this.codDisciplina = codDisciplina;
    }


    @Column(name="cod_curso", nullable=false)
    public int getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(int codCurso) {
        this.codCurso = codCurso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaDisciplinaCursosId) ) return false;
		 TaDisciplinaCursosId castOther = ( TaDisciplinaCursosId ) other; 
         
		 return (this.getCodDisciplina()==castOther.getCodDisciplina())
 && (this.getCodCurso()==castOther.getCodCurso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodDisciplina();
         result = 37 * result + this.getCodCurso();
         return result;
   }   


}


