package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCurso generated by hbm2java
 */
@Entity
@Table(name="tb_curso"
    ,catalog="estreaming"
)
public class TbCurso  implements java.io.Serializable {


     private int idtCurso;
     private TbFaculdade tbFaculdade;
     private String nmeCurso;
     private boolean stsCurso;
     private Date dtaInsercao;
     private int qtdSemestres;
     private String codUsuarioCoordenador;
     private Set<TaUsuarioCursos> taUsuarioCursoses = new HashSet<TaUsuarioCursos>(0);
     private Set<TaDisciplinaCursos> taDisciplinaCursoses = new HashSet<TaDisciplinaCursos>(0);

    public TbCurso() {
    }

	
    public TbCurso(int idtCurso, TbFaculdade tbFaculdade, String nmeCurso, boolean stsCurso, Date dtaInsercao, int qtdSemestres, String codUsuarioCoordenador) {
        this.idtCurso = idtCurso;
        this.tbFaculdade = tbFaculdade;
        this.nmeCurso = nmeCurso;
        this.stsCurso = stsCurso;
        this.dtaInsercao = dtaInsercao;
        this.qtdSemestres = qtdSemestres;
        this.codUsuarioCoordenador = codUsuarioCoordenador;
    }
    public TbCurso(int idtCurso, TbFaculdade tbFaculdade, String nmeCurso, boolean stsCurso, Date dtaInsercao, int qtdSemestres, String codUsuarioCoordenador, Set<TaUsuarioCursos> taUsuarioCursoses, Set<TaDisciplinaCursos> taDisciplinaCursoses) {
       this.idtCurso = idtCurso;
       this.tbFaculdade = tbFaculdade;
       this.nmeCurso = nmeCurso;
       this.stsCurso = stsCurso;
       this.dtaInsercao = dtaInsercao;
       this.qtdSemestres = qtdSemestres;
       this.codUsuarioCoordenador = codUsuarioCoordenador;
       this.taUsuarioCursoses = taUsuarioCursoses;
       this.taDisciplinaCursoses = taDisciplinaCursoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_curso", unique=true, nullable=false)
    public Integer getIdtCurso() {
        return this.idtCurso;
    }
    
    public void setIdtCurso(Integer idtCurso) {
        this.idtCurso = idtCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_faculdade", nullable=false)
    public TbFaculdade getTbFaculdade() {
        return this.tbFaculdade;
    }
    
    public void setTbFaculdade(TbFaculdade tbFaculdade) {
        this.tbFaculdade = tbFaculdade;
    }

    
    @Column(name="nme_curso", nullable=false, length=80)
    public String getNmeCurso() {
        return this.nmeCurso;
    }
    
    public void setNmeCurso(String nmeCurso) {
        this.nmeCurso = nmeCurso;
    }

    
    @Column(name="sts_curso", nullable=false)
    public boolean isStsCurso() {
        return this.stsCurso;
    }
    
    public void setStsCurso(boolean stsCurso) {
        this.stsCurso = stsCurso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_insercao", nullable=false, length=19)
    public Date getDtaInsercao() {
        return this.dtaInsercao;
    }
    
    public void setDtaInsercao(Date dtaInsercao) {
        this.dtaInsercao = dtaInsercao;
    }

    
    @Column(name="qtd_semestres", nullable=false)
    public int getQtdSemestres() {
        return this.qtdSemestres;
    }
    
    public void setQtdSemestres(int qtdSemestres) {
        this.qtdSemestres = qtdSemestres;
    }

    
    @Column(name="cod_usuario_coordenador", nullable=false, length=45)
    public String getCodUsuarioCoordenador() {
        return this.codUsuarioCoordenador;
    }
    
    public void setCodUsuarioCoordenador(String codUsuarioCoordenador) {
        this.codUsuarioCoordenador = codUsuarioCoordenador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCurso")
    public Set<TaUsuarioCursos> getTaUsuarioCursoses() {
        return this.taUsuarioCursoses;
    }
    
    public void setTaUsuarioCursoses(Set<TaUsuarioCursos> taUsuarioCursoses) {
        this.taUsuarioCursoses = taUsuarioCursoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCurso")
    public Set<TaDisciplinaCursos> getTaDisciplinaCursoses() {
        return this.taDisciplinaCursoses;
    }
    
    public void setTaDisciplinaCursoses(Set<TaDisciplinaCursos> taDisciplinaCursoses) {
        this.taDisciplinaCursoses = taDisciplinaCursoses;
    }




}


