package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbDisciplina generated by hbm2java
 */
@Entity
@Table(name="tb_disciplina"
    ,catalog="estreaming"
)
public class TbDisciplina  implements java.io.Serializable {


     private int idtDisciplina;
     private String nmeDisciplina;
     private boolean stsDisciplina;
     private Date dtaInsercao;
     private int semDisciplina;
     private Set<TbAssunto> tbAssuntos = new HashSet<TbAssunto>(0);
     private Set<TaDisciplinaCursos> taDisciplinaCursoses = new HashSet<TaDisciplinaCursos>(0);

    public TbDisciplina() {
    }

	
    public TbDisciplina(int idtDisciplina, String nmeDisciplina, boolean stsDisciplina, Date dtaInsercao, int semDisciplina) {
        this.idtDisciplina = idtDisciplina;
        this.nmeDisciplina = nmeDisciplina;
        this.stsDisciplina = stsDisciplina;
        this.dtaInsercao = dtaInsercao;
        this.semDisciplina = semDisciplina;
    }
    public TbDisciplina(int idtDisciplina, String nmeDisciplina, boolean stsDisciplina, Date dtaInsercao, int semDisciplina, Set<TbAssunto> tbAssuntos, Set<TaDisciplinaCursos> taDisciplinaCursoses) {
       this.idtDisciplina = idtDisciplina;
       this.nmeDisciplina = nmeDisciplina;
       this.stsDisciplina = stsDisciplina;
       this.dtaInsercao = dtaInsercao;
       this.semDisciplina = semDisciplina;
       this.tbAssuntos = tbAssuntos;
       this.taDisciplinaCursoses = taDisciplinaCursoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_disciplina", unique=true, nullable=false)
    public int getIdtDisciplina() {
        return this.idtDisciplina;
    }
    
    public void setIdtDisciplina(int idtDisciplina) {
        this.idtDisciplina = idtDisciplina;
    }

    
    @Column(name="nme_disciplina", nullable=false, length=80)
    public String getNmeDisciplina() {
        return this.nmeDisciplina;
    }
    
    public void setNmeDisciplina(String nmeDisciplina) {
        this.nmeDisciplina = nmeDisciplina;
    }

    
    @Column(name="sts_disciplina", nullable=false)
    public boolean isStsDisciplina() {
        return this.stsDisciplina;
    }
    
    public void setStsDisciplina(boolean stsDisciplina) {
        this.stsDisciplina = stsDisciplina;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_insercao", nullable=false, length=19)
    public Date getDtaInsercao() {
        return this.dtaInsercao;
    }
    
    public void setDtaInsercao(Date dtaInsercao) {
        this.dtaInsercao = dtaInsercao;
    }

    
    @Column(name="sem_disciplina", nullable=false)
    public int getSemDisciplina() {
        return this.semDisciplina;
    }
    
    public void setSemDisciplina(int semDisciplina) {
        this.semDisciplina = semDisciplina;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbDisciplina")
    public Set<TbAssunto> getTbAssuntos() {
        return this.tbAssuntos;
    }
    
    public void setTbAssuntos(Set<TbAssunto> tbAssuntos) {
        this.tbAssuntos = tbAssuntos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbDisciplina")
    public Set<TaDisciplinaCursos> getTaDisciplinaCursoses() {
        return this.taDisciplinaCursoses;
    }
    
    public void setTaDisciplinaCursoses(Set<TaDisciplinaCursos> taDisciplinaCursoses) {
        this.taDisciplinaCursoses = taDisciplinaCursoses;
    }




}


