package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbMultAlternativas generated by hbm2java
 */
@Entity
@Table(name="tb_mult_alternativas"
    ,catalog="estreaming"
)
public class TbMultAlternativas  implements java.io.Serializable {


     private Integer idtAlternativas;
     private TbMultEscolha tbMultEscolha;
     private String txtItem;
     private boolean correto;
     private boolean stsMultAlternativas;

    public TbMultAlternativas() {
    }

    public TbMultAlternativas(TbMultEscolha tbMultEscolha, String txtItem, boolean correto, boolean stsMultAlternativas) {
       this.tbMultEscolha = tbMultEscolha;
       this.txtItem = txtItem;
       this.correto = correto;
       this.stsMultAlternativas = stsMultAlternativas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_alternativas", unique=true, nullable=false)
    public Integer getIdtAlternativas() {
        return this.idtAlternativas;
    }
    
    public void setIdtAlternativas(Integer idtAlternativas) {
        this.idtAlternativas = idtAlternativas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_mult_escolha", nullable=false)
    public TbMultEscolha getTbMultEscolha() {
        return this.tbMultEscolha;
    }
    
    public void setTbMultEscolha(TbMultEscolha tbMultEscolha) {
        this.tbMultEscolha = tbMultEscolha;
    }

    
    @Column(name="txt_item", nullable=false, length=65535)
    public String getTxtItem() {
        return this.txtItem;
    }
    
    public void setTxtItem(String txtItem) {
        this.txtItem = txtItem;
    }

    
    @Column(name="correto", nullable=false)
    public boolean isCorreto() {
        return this.correto;
    }
    
    public void setCorreto(boolean correto) {
        this.correto = correto;
    }

    
    @Column(name="sts_mult_alternativas", nullable=false)
    public boolean isStsMultAlternativas() {
        return this.stsMultAlternativas;
    }
    
    public void setStsMultAlternativas(boolean stsMultAlternativas) {
        this.stsMultAlternativas = stsMultAlternativas;
    }




}


