package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbNotas generated by hbm2java
 */
@Entity
@Table(name="tb_notas"
    ,catalog="estreaming"
)
public class TbNotas  implements java.io.Serializable {


     private TbNotasId id;
     private TbAssunto tbAssunto;
     private TbUsuario tbUsuario;
     private float nota;

    public TbNotas() {
    }

    public TbNotas(TbNotasId id, TbAssunto tbAssunto, TbUsuario tbUsuario, float nota) {
       this.id = id;
       this.tbAssunto = tbAssunto;
       this.tbUsuario = tbUsuario;
       this.nota = nota;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codUsuario", column=@Column(name="cod_usuario", nullable=false) ), 
        @AttributeOverride(name="codAssunto", column=@Column(name="cod_assunto", nullable=false) ) } )
    public TbNotasId getId() {
        return this.id;
    }
    
    public void setId(TbNotasId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_assunto", nullable=false, insertable=false, updatable=false)
    public TbAssunto getTbAssunto() {
        return this.tbAssunto;
    }
    
    public void setTbAssunto(TbAssunto tbAssunto) {
        this.tbAssunto = tbAssunto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_usuario", nullable=false, insertable=false, updatable=false)
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }

    
    @Column(name="nota", nullable=false, precision=12, scale=0)
    public float getNota() {
        return this.nota;
    }
    
    public void setNota(float nota) {
        this.nota = nota;
    }




}


