package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbNotasId generated by hbm2java
 */
@Embeddable
public class TbNotasId  implements java.io.Serializable {


     private int codUsuario;
     private int codAssunto;

    public TbNotasId() {
    }

    public TbNotasId(int codUsuario, int codAssunto) {
       this.codUsuario = codUsuario;
       this.codAssunto = codAssunto;
    }
   


    @Column(name="cod_usuario", nullable=false)
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }


    @Column(name="cod_assunto", nullable=false)
    public int getCodAssunto() {
        return this.codAssunto;
    }
    
    public void setCodAssunto(int codAssunto) {
        this.codAssunto = codAssunto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbNotasId) ) return false;
		 TbNotasId castOther = ( TbNotasId ) other; 
         
		 return (this.getCodUsuario()==castOther.getCodUsuario())
 && (this.getCodAssunto()==castOther.getCodAssunto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodUsuario();
         result = 37 * result + this.getCodAssunto();
         return result;
   }   


}


