package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbSomatorioAlternativas generated by hbm2java
 */
@Entity
@Table(name="tb_somatorio_alternativas"
    ,catalog="estreaming"
)
public class TbSomatorioAlternativas  implements java.io.Serializable {


     private Integer idtSomatorioAlternativas;
     private TbSomatorio tbSomatorio;
     private String txtItem;
     private int vlrSomatorioAlternativas;
     private boolean stsSomatorioAlternativas;

    public TbSomatorioAlternativas() {
    }

    public TbSomatorioAlternativas(TbSomatorio tbSomatorio, String txtItem, int vlrSomatorioAlternativas, boolean stsSomatorioAlternativas) {
       this.tbSomatorio = tbSomatorio;
       this.txtItem = txtItem;
       this.vlrSomatorioAlternativas = vlrSomatorioAlternativas;
       this.stsSomatorioAlternativas = stsSomatorioAlternativas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_somatorio_alternativas", unique=true, nullable=false)
    public Integer getIdtSomatorioAlternativas() {
        return this.idtSomatorioAlternativas;
    }
    
    public void setIdtSomatorioAlternativas(Integer idtSomatorioAlternativas) {
        this.idtSomatorioAlternativas = idtSomatorioAlternativas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_somatorio", nullable=false)
    public TbSomatorio getTbSomatorio() {
        return this.tbSomatorio;
    }
    
    public void setTbSomatorio(TbSomatorio tbSomatorio) {
        this.tbSomatorio = tbSomatorio;
    }

    
    @Column(name="txt_item", nullable=false, length=65535)
    public String getTxtItem() {
        return this.txtItem;
    }
    
    public void setTxtItem(String txtItem) {
        this.txtItem = txtItem;
    }

    
    @Column(name="vlr_somatorio_alternativas", nullable=false)
    public int getVlrSomatorioAlternativas() {
        return this.vlrSomatorioAlternativas;
    }
    
    public void setVlrSomatorioAlternativas(int vlrSomatorioAlternativas) {
        this.vlrSomatorioAlternativas = vlrSomatorioAlternativas;
    }

    
    @Column(name="sts_somatorio_alternativas", nullable=false)
    public boolean isStsSomatorioAlternativas() {
        return this.stsSomatorioAlternativas;
    }
    
    public void setStsSomatorioAlternativas(boolean stsSomatorioAlternativas) {
        this.stsSomatorioAlternativas = stsSomatorioAlternativas;
    }




}


