package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbTipoMidia generated by hbm2java
 */
@Entity
@Table(name="tb_tipo_midia"
    ,catalog="estreaming"
)
public class TbTipoMidia  implements java.io.Serializable {


     private Integer idtTipoMidia;
     private char tpoMidia;
     private boolean stsTipoMidia;
     private Set<TbMidia> tbMidias = new HashSet<TbMidia>(0);

    public TbTipoMidia() {
    }

	
    public TbTipoMidia(char tpoMidia, boolean stsTipoMidia) {
        this.tpoMidia = tpoMidia;
        this.stsTipoMidia = stsTipoMidia;
    }
    public TbTipoMidia(char tpoMidia, boolean stsTipoMidia, Set<TbMidia> tbMidias) {
       this.tpoMidia = tpoMidia;
       this.stsTipoMidia = stsTipoMidia;
       this.tbMidias = tbMidias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_tipo_midia", unique=true, nullable=false)
    public Integer getIdtTipoMidia() {
        return this.idtTipoMidia;
    }
    
    public void setIdtTipoMidia(Integer idtTipoMidia) {
        this.idtTipoMidia = idtTipoMidia;
    }

    
    @Column(name="tpo_midia", nullable=false, length=1)
    public char getTpoMidia() {
        return this.tpoMidia;
    }
    
    public void setTpoMidia(char tpoMidia) {
        this.tpoMidia = tpoMidia;
    }

    
    @Column(name="sts_tipo_midia", nullable=false)
    public boolean isStsTipoMidia() {
        return this.stsTipoMidia;
    }
    
    public void setStsTipoMidia(boolean stsTipoMidia) {
        this.stsTipoMidia = stsTipoMidia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbTipoMidia")
    public Set<TbMidia> getTbMidias() {
        return this.tbMidias;
    }
    
    public void setTbMidias(Set<TbMidia> tbMidias) {
        this.tbMidias = tbMidias;
    }




}


