package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbUsuario generated by hbm2java
 */
@Entity
@Table(name="tb_usuario"
    ,catalog="estreaming"
)
public class TbUsuario  implements java.io.Serializable {


     private Integer idtUsuario;
     private String cpfUsuario;
     private String nmeUsuario;
     private String emlUsuario;
     private String pwdUsuario;
     private char tpoUsuario;
     private Date dtaInsercao;
     private boolean stsUsuario;
     private String lgnEspecial;
     private int telUsuario;
     private Set<TaUsuarioFaculdade> taUsuarioFaculdades = new HashSet<TaUsuarioFaculdade>(0);
     private Set<TaUsuarioCursos> taUsuarioCursoses = new HashSet<TaUsuarioCursos>(0);
     private Set<TbNotas> tbNotases = new HashSet<TbNotas>(0);

    public TbUsuario() {
    }

	
    public TbUsuario(String cpfUsuario, String nmeUsuario, String emlUsuario, String pwdUsuario, char tpoUsuario, Date dtaInsercao, boolean stsUsuario, int telUsuario) {
        this.cpfUsuario = cpfUsuario;
        this.nmeUsuario = nmeUsuario;
        this.emlUsuario = emlUsuario;
        this.pwdUsuario = pwdUsuario;
        this.tpoUsuario = tpoUsuario;
        this.dtaInsercao = dtaInsercao;
        this.stsUsuario = stsUsuario;
        this.telUsuario = telUsuario;
    }
    public TbUsuario(String cpfUsuario, String nmeUsuario, String emlUsuario, String pwdUsuario, char tpoUsuario, Date dtaInsercao, boolean stsUsuario, String lgnEspecial, int telUsuario, Set<TaUsuarioFaculdade> taUsuarioFaculdades, Set<TaUsuarioCursos> taUsuarioCursoses, Set<TbNotas> tbNotases) {
       this.cpfUsuario = cpfUsuario;
       this.nmeUsuario = nmeUsuario;
       this.emlUsuario = emlUsuario;
       this.pwdUsuario = pwdUsuario;
       this.tpoUsuario = tpoUsuario;
       this.dtaInsercao = dtaInsercao;
       this.stsUsuario = stsUsuario;
       this.lgnEspecial = lgnEspecial;
       this.telUsuario = telUsuario;
       this.taUsuarioFaculdades = taUsuarioFaculdades;
       this.taUsuarioCursoses = taUsuarioCursoses;
       this.tbNotases = tbNotases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_usuario", unique=true, nullable=false)
    public Integer getIdtUsuario() {
        return this.idtUsuario;
    }
    
    public void setIdtUsuario(Integer idtUsuario) {
        this.idtUsuario = idtUsuario;
    }

    
    @Column(name="cpf_usuario", nullable=false, length=11)
    public String getCpfUsuario() {
        return this.cpfUsuario;
    }
    
    public void setCpfUsuario(String cpfUsuario) {
        this.cpfUsuario = cpfUsuario;
    }

    
    @Column(name="nme_usuario", nullable=false, length=80)
    public String getNmeUsuario() {
        return this.nmeUsuario;
    }
    
    public void setNmeUsuario(String nmeUsuario) {
        this.nmeUsuario = nmeUsuario;
    }

    
    @Column(name="eml_usuario", nullable=false, length=80)
    public String getEmlUsuario() {
        return this.emlUsuario;
    }
    
    public void setEmlUsuario(String emlUsuario) {
        this.emlUsuario = emlUsuario;
    }

    
    @Column(name="pwd_usuario", nullable=false, length=128)
    public String getPwdUsuario() {
        return this.pwdUsuario;
    }
    
    public void setPwdUsuario(String pwdUsuario) {
        this.pwdUsuario = pwdUsuario;
    }

    
    @Column(name="tpo_usuario", nullable=false, length=1)
    public char getTpoUsuario() {
        return this.tpoUsuario;
    }
    
    public void setTpoUsuario(char tpoUsuario) {
        this.tpoUsuario = tpoUsuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_insercao", nullable=false, length=19)
    public Date getDtaInsercao() {
        return this.dtaInsercao;
    }
    
    public void setDtaInsercao(Date dtaInsercao) {
        this.dtaInsercao = dtaInsercao;
    }

    
    @Column(name="sts_usuario", nullable=false)
    public boolean isStsUsuario() {
        return this.stsUsuario;
    }
    
    public void setStsUsuario(boolean stsUsuario) {
        this.stsUsuario = stsUsuario;
    }

    
    @Column(name="lgn_especial", length=20)
    public String getLgnEspecial() {
        return this.lgnEspecial;
    }
    
    public void setLgnEspecial(String lgnEspecial) {
        this.lgnEspecial = lgnEspecial;
    }

    
    @Column(name="tel_usuario", nullable=false)
    public int getTelUsuario() {
        return this.telUsuario;
    }
    
    public void setTelUsuario(int telUsuario) {
        this.telUsuario = telUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbUsuario")
    public Set<TaUsuarioFaculdade> getTaUsuarioFaculdades() {
        return this.taUsuarioFaculdades;
    }
    
    public void setTaUsuarioFaculdades(Set<TaUsuarioFaculdade> taUsuarioFaculdades) {
        this.taUsuarioFaculdades = taUsuarioFaculdades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbUsuario")
    public Set<TaUsuarioCursos> getTaUsuarioCursoses() {
        return this.taUsuarioCursoses;
    }
    
    public void setTaUsuarioCursoses(Set<TaUsuarioCursos> taUsuarioCursoses) {
        this.taUsuarioCursoses = taUsuarioCursoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbUsuario")
    public Set<TbNotas> getTbNotases() {
        return this.tbNotases;
    }
    
    public void setTbNotases(Set<TbNotas> tbNotases) {
        this.tbNotases = tbNotases;
    }




}


