package model;
// Generated 21/10/2017 10:26:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbVF generated by hbm2java
 */
@Entity
@Table(name="tb_v_f"
    ,catalog="estreaming"
)
public class TbVF  implements java.io.Serializable {


     private Integer idtVf;
     private TbAssunto tbAssunto;
     private TbTipoQuestao tbTipoQuestao;
     private boolean stsVF;
     private String txtEnunciado;
     private int ordVF;
     private Date dtaInsercao;
     private char flgFinalizada;
     private Set<TbVFAlternativas> tbVFAlternativases = new HashSet<TbVFAlternativas>(0);

    public TbVF() {
    }

	
    public TbVF(TbAssunto tbAssunto, TbTipoQuestao tbTipoQuestao, boolean stsVF, String txtEnunciado, int ordVF, Date dtaInsercao, char flgFinalizada) {
        this.tbAssunto = tbAssunto;
        this.tbTipoQuestao = tbTipoQuestao;
        this.stsVF = stsVF;
        this.txtEnunciado = txtEnunciado;
        this.ordVF = ordVF;
        this.dtaInsercao = dtaInsercao;
        this.flgFinalizada = flgFinalizada;
    }
    public TbVF(TbAssunto tbAssunto, TbTipoQuestao tbTipoQuestao, boolean stsVF, String txtEnunciado, int ordVF, Date dtaInsercao, char flgFinalizada, Set<TbVFAlternativas> tbVFAlternativases) {
       this.tbAssunto = tbAssunto;
       this.tbTipoQuestao = tbTipoQuestao;
       this.stsVF = stsVF;
       this.txtEnunciado = txtEnunciado;
       this.ordVF = ordVF;
       this.dtaInsercao = dtaInsercao;
       this.flgFinalizada = flgFinalizada;
       this.tbVFAlternativases = tbVFAlternativases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_vf", unique=true, nullable=false)
    public Integer getIdtVf() {
        return this.idtVf;
    }
    
    public void setIdtVf(Integer idtVf) {
        this.idtVf = idtVf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_assunto", nullable=false)
    public TbAssunto getTbAssunto() {
        return this.tbAssunto;
    }
    
    public void setTbAssunto(TbAssunto tbAssunto) {
        this.tbAssunto = tbAssunto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_tipo_questao", nullable=false)
    public TbTipoQuestao getTbTipoQuestao() {
        return this.tbTipoQuestao;
    }
    
    public void setTbTipoQuestao(TbTipoQuestao tbTipoQuestao) {
        this.tbTipoQuestao = tbTipoQuestao;
    }

    
    @Column(name="sts_v_f", nullable=false)
    public boolean isStsVF() {
        return this.stsVF;
    }
    
    public void setStsVF(boolean stsVF) {
        this.stsVF = stsVF;
    }

    
    @Column(name="txt_enunciado", nullable=false, length=65535)
    public String getTxtEnunciado() {
        return this.txtEnunciado;
    }
    
    public void setTxtEnunciado(String txtEnunciado) {
        this.txtEnunciado = txtEnunciado;
    }

    
    @Column(name="ord_v_f", nullable=false)
    public int getOrdVF() {
        return this.ordVF;
    }
    
    public void setOrdVF(int ordVF) {
        this.ordVF = ordVF;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dta_insercao", nullable=false, length=19)
    public Date getDtaInsercao() {
        return this.dtaInsercao;
    }
    
    public void setDtaInsercao(Date dtaInsercao) {
        this.dtaInsercao = dtaInsercao;
    }

    
    @Column(name="flg_finalizada", nullable=false, length=1)
    public char getFlgFinalizada() {
        return this.flgFinalizada;
    }
    
    public void setFlgFinalizada(char flgFinalizada) {
        this.flgFinalizada = flgFinalizada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbVF")
    public Set<TbVFAlternativas> getTbVFAlternativases() {
        return this.tbVFAlternativases;
    }
    
    public void setTbVFAlternativases(Set<TbVFAlternativas> tbVFAlternativases) {
        this.tbVFAlternativases = tbVFAlternativases;
    }




}


